### ISSUE TITLE
Possible to move only one foot with topic ?

### ISSUE THREAD

**Issue by elpimous** [qiayuanliao/legged_control#44]
Hello all, can I move one foot with topic ? 
ex : displace a foot  x=0.10, y=0.0, z=0.25, and let ocs2 calculate body stability
My end idea is to use some sequences to make robot danse between 2 walks

this way ? rostopic pub -1 /legged_robot/desiredFeetTrajectory/LF
```
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
ns: ''
id: 0
type: 0
action: 0
pose:
  position: {x: 0.0, y: 0.0, z: 0.20}
  orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
scale: {x: 0.0, y: 0.0, z: 0.0}
color: {r: 0.0, g: 0.0, b: 0.0, a: 0.0}
lifetime: {secs: 2.0, nsecs: 0}
frame_locked: false
points:
- {x: 0.0, y: 0.0, z: 0.0}
colors:
- {r: 0.0, g: 0.0, b: 0.0, a: 0.0}
text: ''
mesh_resource: ''
mesh_use_embedded_materials: false" 
```
